import localFont from "next/font/local";
import { Sanchez } from "@next/font/google";
import { Inter } from "@next/font/google";
import { Poppins, Roboto, Nunito, Miniver } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // Add specific weights as needed
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // Add specific weights as needed
  variable: "--font-roboto",
});

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"], // Add specific weights as needed
  variable: "--font-nunito",
});

const miniver = Miniver({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-miniver",
});

const inter = Inter({ subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const sanchez = Sanchez({
  subsets: ["latin"],
  variable: "--font-sanchez",
  weight: "400",
});

export const metadata = {
  title: "Breakfast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sanchez.variable} ${inter.variable} ${poppins.variable} ${roboto.variable} ${nunito.variable} ${miniver.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
