import localFont from "next/font/local";
import { Sanchez } from "@next/font/google";
import { Inter } from "@next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const sanchez = Sanchez({
  subsets: ["latin"],
  variable: "--font-sanchez",
  weight: "400",
});

export const metadata = {
  title: "Breakfast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sanchez.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
